### ISSUE TITLE
Different use of queryNamePattern

### ISSUE THREAD

**Issue by marcelloh** [midir99/sqload#1]
I'm write a migration tool and this is how it works (because I have to use "-- query:" as a pattern:
```
	sqlStatements, err := sqload.LoadFromString[struct {
		MigrateUp   string `query:"migrateUp"`
		MigrateDown string `query:"migrateDown"`
	}](string(fileData))
```
but it would be nice if the pattern was derived from the struct itself, then I could do:
```
	sqlStatements, err := sqload.LoadFromString[struct {
		MigrateUp   string `migrate:"migrateUp"`
		MigrateDown string `migrate:"Down"`
	}](string(fileData))
```

**Comment by midir99** [comment]
Hey @marcelloh, hope you are doing fine!

So basically, what you are suggesting is the feature to use any identifier (`-- query`, `-- migrate`, etc..) as the comment above the SQL query needed by the loader to identify the body of the SQL query right? I'm asking this just to make sure I understand the proposal 😋

**Comment by midir99** [comment]
I've been thinking about this and I'm thinking of a more general-purpose tool to load any type of text desired by user, not only SQL queries, obviously user can load any kind of text from a file using the `-- query` identifier but probably I'll create a tool called `textload`, and instead of `-- query` it would simply be `-- text`. Anyway, I don't know if this would still be relevant since go has a module to embed text into strings...

I'm really sorry for answering this late, the previous year was simply crazy :(.

**Comment by marcelloh** [comment]
Sorry, time moved on and from end 2022 till now seems like a decade.
I hope it has been positively crazy for you ;-)
